- type: antag
  id: Scp2054X
  name: ghost-role-information-scp-2054-x-name
  antagonist: true
  objective: roles-antag-paradox-clone-objective
  setPreference: false
  playTimeTracker: AntagParadoxClone # Sunrise-Edit
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 часов
