- type: entity
  id: ScpClosetBombFilled
  parent: ScpClosetBomb
  suffix: Filled
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetBomb
